name: Learn github actions

on: push

jobs:
    test-linux-commands:
        runs-on: ubuntu-latest

        steps:
            - name: Run Linux Commands
              run: |
                pwd
                ls
                whoami
                date
            
