name: Learn github actions

on: push

jobs:
    test-linux-commands:
        runs-on: ubuntu-latest

        steps:
            - name: Run Linux Commands
              run: |
                echo "current working directory"
                pwd

                echo "current user"
                whoami

                echo "current data"
                data

                mkdir test-folder

                echo "hello from github actions" > test-folder/hello.txt

                echo "file content"
                cat test-folder/hello.txt
            
