name: Learn github actions

on:
    push:
        branches: 
            - main
        
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - run: echo "This is due some one pushed code on main branch"
    
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                    node-version: 24
            - run: npm install 
            - run : npm run build
            - run : echo "Nest build is successfully built see on github actions"
